### ISSUE TITLE
Amulet tests are failing.

### ISSUE THREAD

**Issue by ktsakalozos** [jenkinsci/jenkins-charm#14]
I got some amulet tests failing: http://pastebin.ubuntu.com/23746603/

Thanks

**Comment by freeekanayaka** [comment]
Konstantinos Tsakalozos <notifications@github.com> writes:

> I got some amulet tests failing: http://pastebin.ubuntu.com/23746603/

I'll try to give a look at that tomorrow.

**Comment by freeekanayaka** [comment]
I haven't been able to reproduce the first failure (test_10_change_plugins):

http://pastebin.ubuntu.com/23751570/

Note that I ran the test directly, since at the moment bundletester is failing in weird way for me (I've installed it from pip), this should make no difference tho.

If get this failure consistently, please would you attach the full juju log for the unit?

**Comment by freeekanayaka** [comment]
I was instead able to reproduce the second failure, which turns out to be a genuine regression in the charm introduced by stricter checks of the slave launcher type that are performed by the Jenkins master starting from version 2.27.

I'm going to push a PR to fix it.

**Comment by tkuhlman** [comment]
I've seen that first failure once but on rerun it was gone, so I suspect it is timing related.
