### ISSUE TITLE
support: New API token system in Jenkins 2.129+

### ISSUE THREAD

**Issue by jamesbeedy** [jenkinsci/jenkins-charm#47]
Default api tokens are disabled since jenkins 2.1.29, see https://jenkins.io/blog/2018/07/02/new-api-token-system/.

The jenkins-charm needs a way to handle the new api token default behavior when initializing.
This seems to be the root cause of a bunch of the current issues.

**Comment by jamesbeedy** [comment]
bump

**Comment by mthaddon** [comment]
See https://github.com/mthaddon/jenkins-charm/tree/new-api-token - I still need to test this before proposing a PR

**Comment by jamesbeedy** [comment]
Thanks @mthaddon ! 

I gave your code a build/deploy and am seeing this in the logs https://paste.ubuntu.com/p/ngdZmRxF8Z/

**Comment by mthaddon** [comment]
I'm getting a slightly different error - https://pastebin.ubuntu.com/p/y3SSQYfN8t/ - in any case, plan to keep digging and will see what I can find.

**Comment by jamesbeedy** [comment]
I wasn't using your `new-api-token` branch. I'm getting the same error as you now.

**Comment by jetpackdanger** [comment]
These errors are because fresh builds of the charm get a version of python-jenkins that uses requests, whereas api.py expects the old urrlib-based code. Here's a PR to fix it: https://github.com/jenkinsci/jenkins-charm/pull/50

Tom's branch above needs a light rebase for this change, which I've done and pushed to https://github.com/jetpackdanger/jenkins-charm/tree/new-api-token-2

**Comment by mthaddon** [comment]
This is now fixed as of cs:jenkins-15
